name: CI .NET 6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `postgres-job` executes in
    container: node:latest

    # service containers to run with `postgres-job`
    services:
      # label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # service environment variables
        # `POSTGRES_HOST` is `postgres`
        env:
          # required
          POSTGRES_PASSWORD: 1234
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: Adrian
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x 
      
      - name: Clone shared repository
        run: | 
          cd ..
          git clone https://github.com/Nairda015/Warbud.Shared
          dir
      
      - name: Restore Packages
        run: dotnet restore

      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/Warbud.Users.Api/appsettings.json'
          name: "ConnectionString"
          connectionstring: "User ID = postgres; Password = admin; Server = postgres; Port = 5432; Database = WarbudDb; Integrated Security = true; Pooling = true;"
          
      - name: Print ConnectionString
        run: | 
          cd '${{ github.workspace }}/Warbud.Users.Api'
          dir
          cat .\appsettings.json
      
      - name: Build
        run: dotnet build -c Release  --no-restore
      
      - name: run migrations
        run: |
          export PATH="$PATH:/github/home/.dotnet/tools"
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dir
          cd Warbud.Users.Infrastructure
          dotnet ef migrations add Testes -s ../Warbud.Users.Api -c WriteDbContext
          dotnet ef database update -s ../Warbud.Users.Api -c WriteDbContext
      
      - name: Test
        run: dotnet test -c Release
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: 1234
          POSTGRES_USER: Adrian
