name: CI .NET 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Print 1
        run: |
          dir
          cd ..
          dir

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x 
      
      - name: Clone shared repository
        run: git clone https://github.com/Nairda015/Warbud.Shared

      - name: Print 2
        run: |
          dir
          cd ..
          dir
      
      - name: Restore Packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release  --no-restore
      
      - name: Test
        run: dotnet test -c Release
